from __future__ import annotations

from datetime import UTC, datetime, timedelta

from sqlalchemy import create_engine, text
from sqlalchemy.engine import RowMapping

from research_agents.reports.models import ResearchReport
from research_agents.storage.sqlite import BatchItemRecord, BatchRecord, ReportRecord


class PostgresReportStore:
    def __init__(self, database_url: str) -> None:
        self.database_url = database_url
        self._engine = create_engine(database_url, pool_pre_ping=True)
        self.initialize()

    def initialize(self) -> None:
        with self._engine.begin() as connection:
            connection.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS reports (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ticker TEXT NOT NULL,
                        analysis_date TEXT NOT NULL,
                        data_source TEXT NOT NULL,
                        status TEXT NOT NULL,
                        attempts INTEGER NOT NULL DEFAULT 0,
                        max_attempts INTEGER NOT NULL DEFAULT 3,
                        decision TEXT,
                        confidence DOUBLE PRECISION,
                        report_json TEXT,
                        markdown TEXT,
                        error TEXT,
                        last_error TEXT,
                        created_at TEXT NOT NULL,
                        updated_at TEXT NOT NULL,
                        started_at TEXT,
                        finished_at TEXT,
                        batch_id INTEGER,
                        portfolio_context_json TEXT
                    )
                    """
                )
            )
            connection.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS report_batches (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status TEXT NOT NULL,
                        total INTEGER NOT NULL,
                        queued INTEGER NOT NULL,
                        running INTEGER NOT NULL,
                        completed INTEGER NOT NULL,
                        failed INTEGER NOT NULL,
                        data_source TEXT NOT NULL,
                        requested_analysis_date TEXT,
                        concurrency INTEGER NOT NULL,
                        created_at TEXT NOT NULL,
                        updated_at TEXT NOT NULL,
                        started_at TEXT,
                        finished_at TEXT,
                        portfolio_context_json TEXT
                    )
                    """
                )
            )
            connection.execute(
                text(
                    """
                    CREATE TABLE IF NOT EXISTS report_batch_items (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        batch_id INTEGER NOT NULL REFERENCES report_batches(id),
                        ticker TEXT NOT NULL,
                        status TEXT NOT NULL,
                        analysis_date TEXT,
                        report_id INTEGER REFERENCES reports(id),
                        decision TEXT,
                        confidence DOUBLE PRECISION,
                        error TEXT,
                        created_at TEXT NOT NULL,
                        updated_at TEXT NOT NULL,
                        started_at TEXT,
                        finished_at TEXT
                    )
                    """
                )
            )
            connection.execute(text("CREATE INDEX IF NOT EXISTS idx_reports_ticker_date ON reports(ticker, analysis_date)"))
            connection.execute(text("CREATE INDEX IF NOT EXISTS idx_reports_batch_id ON reports(batch_id)"))
            connection.execute(text("CREATE INDEX IF NOT EXISTS idx_batch_items_batch_id ON report_batch_items(batch_id)"))
            connection.execute(text("ALTER TABLE reports ADD COLUMN IF NOT EXISTS portfolio_context_json TEXT"))
            connection.execute(text("ALTER TABLE report_batches ADD COLUMN IF NOT EXISTS portfolio_context_json TEXT"))

    def create_queued(
        self,
        ticker: str,
        analysis_date: str,
        data_source: str,
        max_attempts: int = 3,
        batch_id: int | None = None,
        portfolio_context_json: str | None = None,
    ) -> ReportRecord:
        now = _now()
        with self._engine.begin() as connection:
            report_id = connection.execute(
                text(
                    """
                    INSERT INTO reports (
                        ticker, analysis_date, data_source, status, attempts, max_attempts,
                        created_at, updated_at, batch_id, portfolio_context_json
                    ) VALUES (:ticker, :analysis_date, :data_source, :status, :attempts, :max_attempts,
                              :created_at, :updated_at, :batch_id, :portfolio_context_json)
                    RETURNING id
                    """
                ),
                {
                    "ticker": ticker,
                    "analysis_date": analysis_date,
                    "data_source": data_source,
                    "status": "queued",
                    "attempts": 0,
                    "max_attempts": max_attempts,
                    "created_at": now,
                    "updated_at": now,
                    "batch_id": batch_id,
                    "portfolio_context_json": portfolio_context_json,
                },
            ).scalar_one()
        record = self.get(int(report_id))
        if record is None:
            raise RuntimeError("Created report row could not be loaded.")
        return record

    def create_pending(self, ticker: str, analysis_date: str, data_source: str) -> ReportRecord:
        return self.create_queued(ticker, analysis_date, data_source)

    def create_batch(
        self,
        tickers: list[str],
        requested_analysis_date: str | None,
        data_source: str,
        concurrency: int,
        portfolio_context_json: str | None = None,
    ) -> BatchRecord:
        now = _now()
        normalized = [ticker.upper() for ticker in tickers]
        with self._engine.begin() as connection:
            batch_id = connection.execute(
                text(
                    """
                    INSERT INTO report_batches (
                        status, total, queued, running, completed, failed, data_source,
                        requested_analysis_date, concurrency, created_at, updated_at, portfolio_context_json
                    ) VALUES (:status, :total, :queued, :running, :completed, :failed, :data_source,
                              :requested_analysis_date, :concurrency, :created_at, :updated_at, :portfolio_context_json)
                    RETURNING id
                    """
                ),
                {
                    "status": "queued",
                    "total": len(normalized),
                    "queued": len(normalized),
                    "running": 0,
                    "completed": 0,
                    "failed": 0,
                    "data_source": data_source,
                    "requested_analysis_date": requested_analysis_date,
                    "concurrency": concurrency,
                    "created_at": now,
                    "updated_at": now,
                    "portfolio_context_json": portfolio_context_json,
                },
            ).scalar_one()
            connection.execute(
                text(
                    """
                    INSERT INTO report_batch_items (batch_id, ticker, status, created_at, updated_at)
                    VALUES (:batch_id, :ticker, :status, :created_at, :updated_at)
                    """
                ),
                [
                    {
                        "batch_id": int(batch_id),
                        "ticker": ticker,
                        "status": "queued",
                        "created_at": now,
                        "updated_at": now,
                    }
                    for ticker in normalized
                ],
            )
        batch = self.get_batch(int(batch_id))
        if batch is None:
            raise RuntimeError("Created batch row could not be loaded.")
        return batch

    def mark_batch_running(self, batch_id: int) -> BatchRecord:
        now = _now()
        row = self._fetchone("SELECT * FROM report_batches WHERE id = :id", {"id": batch_id})
        if row is None:
            raise ValueError(f"Batch {batch_id} not found.")
        if row["status"] != "running":
            if row["status"] not in {"queued", "completed_with_errors", "failed"}:
                raise ValueError(f"Batch {batch_id} cannot be started from status {row['status']}.")
            self._execute(
                """
                UPDATE report_batches
                SET status = :status, started_at = COALESCE(started_at, :started_at),
                    finished_at = NULL, updated_at = :updated_at
                WHERE id = :id
                """,
                {"status": "running", "started_at": now, "updated_at": now, "id": batch_id},
            )
        self._refresh_batch_counts(batch_id)
        batch = self.get_batch(batch_id)
        if batch is None:
            raise RuntimeError("Running batch row could not be loaded.")
        return batch

    def mark_batch_item_running(self, item_id: int, analysis_date: str) -> BatchItemRecord:
        now = _now()
        row = self._fetchone("SELECT * FROM report_batch_items WHERE id = :id", {"id": item_id})
        if row is None:
            raise ValueError(f"Batch item {item_id} not found.")
        if row["status"] != "queued":
            raise ValueError(f"Batch item {item_id} is not queued.")
        self._execute(
            """
            UPDATE report_batch_items
            SET status = :status, analysis_date = :analysis_date, error = NULL,
                started_at = :started_at, finished_at = NULL, updated_at = :updated_at
            WHERE id = :id
            """,
            {
                "status": "running",
                "analysis_date": analysis_date,
                "started_at": now,
                "updated_at": now,
                "id": item_id,
            },
        )
        item = self.get_batch_item(item_id)
        if item is None:
            raise RuntimeError("Running batch item row could not be loaded.")
        self._refresh_batch_counts(item.batch_id)
        return item

    def mark_batch_item_completed(self, item_id: int, report: ReportRecord) -> BatchItemRecord:
        now = _now()
        self._execute(
            """
            UPDATE report_batch_items
            SET status = :status, report_id = :report_id, decision = :decision, confidence = :confidence,
                error = NULL, finished_at = :finished_at, updated_at = :updated_at
            WHERE id = :id
            """,
            {
                "status": "completed",
                "report_id": report.id,
                "decision": report.decision,
                "confidence": report.confidence,
                "finished_at": now,
                "updated_at": now,
                "id": item_id,
            },
        )
        item = self.get_batch_item(item_id)
        if item is None:
            raise RuntimeError("Completed batch item row could not be loaded.")
        self._refresh_batch_counts(item.batch_id)
        return item

    def mark_batch_item_failed(self, item_id: int, error: str, report_id: int | None = None) -> BatchItemRecord:
        now = _now()
        self._execute(
            """
            UPDATE report_batch_items
            SET status = :status, report_id = COALESCE(:report_id, report_id), error = :error,
                finished_at = :finished_at, updated_at = :updated_at
            WHERE id = :id
            """,
            {
                "status": "failed",
                "report_id": report_id,
                "error": error,
                "finished_at": now,
                "updated_at": now,
                "id": item_id,
            },
        )
        item = self.get_batch_item(item_id)
        if item is None:
            raise RuntimeError("Failed batch item row could not be loaded.")
        self._refresh_batch_counts(item.batch_id)
        return item

    def finalize_batch(self, batch_id: int) -> BatchRecord:
        self._refresh_batch_counts(batch_id)
        batch = self.get_batch(batch_id)
        if batch is None:
            raise ValueError(f"Batch {batch_id} not found.")
        if batch.running or batch.queued:
            return batch
        status = "completed" if batch.completed == batch.total else "failed" if batch.failed == batch.total else "completed_with_errors"
        now = _now()
        self._execute(
            "UPDATE report_batches SET status = :status, finished_at = :finished_at, updated_at = :updated_at WHERE id = :id",
            {"status": status, "finished_at": now, "updated_at": now, "id": batch_id},
        )
        finalized = self.get_batch(batch_id)
        if finalized is None:
            raise RuntimeError("Finalized batch row could not be loaded.")
        return finalized

    def retry_failed_batch_items(self, batch_id: int) -> BatchRecord:
        now = _now()
        row = self._fetchone("SELECT * FROM report_batches WHERE id = :id", {"id": batch_id})
        if row is None:
            raise ValueError(f"Batch {batch_id} not found.")
        if row["status"] not in {"completed_with_errors", "failed"}:
            raise ValueError(f"Batch {batch_id} cannot retry failed items from status {row['status']}.")
        rowcount = self._execute(
            """
            UPDATE report_batch_items
            SET status = :status, report_id = NULL, decision = NULL, confidence = NULL, error = NULL,
                started_at = NULL, finished_at = NULL, updated_at = :updated_at
            WHERE batch_id = :batch_id AND status = :failed_status
            """,
            {"status": "queued", "updated_at": now, "batch_id": batch_id, "failed_status": "failed"},
        )
        if rowcount == 0:
            raise ValueError(f"Batch {batch_id} has no failed items to retry.")
        self._execute(
            "UPDATE report_batches SET status = :status, finished_at = NULL, updated_at = :updated_at WHERE id = :id",
            {"status": "queued", "updated_at": now, "id": batch_id},
        )
        self._refresh_batch_counts(batch_id)
        batch = self.get_batch(batch_id)
        if batch is None:
            raise RuntimeError("Retried batch row could not be loaded.")
        return batch

    def mark_running(self, report_id: int) -> ReportRecord:
        now = _now()
        row = self._fetchone("SELECT * FROM reports WHERE id = :id", {"id": report_id})
        if row is None:
            raise ValueError(f"Report {report_id} not found.")
        if row["status"] != "queued":
            raise ValueError(f"Report {report_id} is not queued.")
        if int(row["attempts"]) >= int(row["max_attempts"]):
            raise ValueError(f"Report {report_id} has reached max attempts.")
        self._execute(
            """
            UPDATE reports
            SET status = :status, attempts = attempts + 1, started_at = :started_at, finished_at = NULL,
                error = NULL, last_error = NULL, updated_at = :updated_at
            WHERE id = :id
            """,
            {"status": "running", "started_at": now, "updated_at": now, "id": report_id},
        )
        record = self.get(report_id)
        if record is None:
            raise RuntimeError("Running report row could not be loaded.")
        return record

    def mark_completed(self, report_id: int, report: ResearchReport, markdown: str) -> ReportRecord:
        now = _now()
        self._execute(
            """
            UPDATE reports
            SET status = :status, decision = :decision, confidence = :confidence, report_json = :report_json,
                markdown = :markdown, error = NULL, last_error = NULL, finished_at = :finished_at, updated_at = :updated_at
            WHERE id = :id
            """,
            {
                "status": "completed",
                "decision": report.decision,
                "confidence": report.confidence,
                "report_json": report.model_dump_json(),
                "markdown": markdown,
                "finished_at": now,
                "updated_at": now,
                "id": report_id,
            },
        )
        record = self.get(report_id)
        if record is None:
            raise RuntimeError("Completed report row could not be loaded.")
        return record

    def mark_failed(self, report_id: int, error: str) -> ReportRecord:
        now = _now()
        self._execute(
            """
            UPDATE reports
            SET status = :status, error = :error, last_error = :last_error, finished_at = :finished_at, updated_at = :updated_at
            WHERE id = :id
            """,
            {"status": "failed", "error": error, "last_error": error, "finished_at": now, "updated_at": now, "id": report_id},
        )
        record = self.get(report_id)
        if record is None:
            raise RuntimeError("Failed report row could not be loaded.")
        return record

    def retry(self, report_id: int) -> ReportRecord:
        now = _now()
        row = self._fetchone("SELECT * FROM reports WHERE id = :id", {"id": report_id})
        if row is None:
            raise ValueError(f"Report {report_id} not found.")
        if row["status"] not in {"failed"}:
            raise ValueError(f"Report {report_id} cannot be retried from status {row['status']}.")
        if int(row["attempts"]) >= int(row["max_attempts"]):
            raise ValueError(f"Report {report_id} has reached max attempts.")
        self._execute(
            """
            UPDATE reports
            SET status = :status, decision = NULL, confidence = NULL, report_json = NULL, markdown = NULL,
                error = NULL, last_error = NULL, started_at = NULL, finished_at = NULL, updated_at = :updated_at
            WHERE id = :id
            """,
            {"status": "queued", "updated_at": now, "id": report_id},
        )
        record = self.get(report_id)
        if record is None:
            raise RuntimeError("Retried report row could not be loaded.")
        return record

    def recover_stale_running(self, timeout_minutes: int = 30) -> int:
        cutoff = datetime.now(tz=UTC) - timedelta(minutes=timeout_minutes)
        now = _now()
        message = "Task timed out or server stopped during execution."
        return self._execute(
            """
            UPDATE reports
            SET status = :status, error = :error, last_error = :last_error, finished_at = :finished_at, updated_at = :updated_at
            WHERE status = :running_status AND started_at IS NOT NULL AND started_at < :cutoff
            """,
            {
                "status": "failed",
                "error": message,
                "last_error": message,
                "finished_at": now,
                "updated_at": now,
                "running_status": "running",
                "cutoff": cutoff.isoformat(),
            },
        )

    def get(self, report_id: int) -> ReportRecord | None:
        row = self._fetchone("SELECT * FROM reports WHERE id = :id", {"id": report_id})
        return _record_from_row(row) if row is not None else None

    def get_batch(self, batch_id: int) -> BatchRecord | None:
        row = self._fetchone("SELECT * FROM report_batches WHERE id = :id", {"id": batch_id})
        return _batch_from_row(row) if row is not None else None

    def get_batch_item(self, item_id: int) -> BatchItemRecord | None:
        row = self._fetchone("SELECT * FROM report_batch_items WHERE id = :id", {"id": item_id})
        return _batch_item_from_row(row) if row is not None else None

    def list_batch_items(self, batch_id: int) -> list[BatchItemRecord]:
        rows = self._fetchall("SELECT * FROM report_batch_items WHERE batch_id = :batch_id ORDER BY id", {"batch_id": batch_id})
        return [_batch_item_from_row(row) for row in rows]

    def list_queued_batch_items(self, batch_id: int) -> list[BatchItemRecord]:
        rows = self._fetchall(
            "SELECT * FROM report_batch_items WHERE batch_id = :batch_id AND status = :status ORDER BY id",
            {"batch_id": batch_id, "status": "queued"},
        )
        return [_batch_item_from_row(row) for row in rows]

    def list_recent(self, limit: int = 20) -> list[ReportRecord]:
        rows = self._fetchall("SELECT * FROM reports ORDER BY id DESC LIMIT :limit", {"limit": limit})
        return [_record_from_row(row) for row in rows]

    def _refresh_batch_counts(self, batch_id: int) -> None:
        now = _now()
        rows = self._fetchall(
            "SELECT status, COUNT(*) AS count FROM report_batch_items WHERE batch_id = :batch_id GROUP BY status",
            {"batch_id": batch_id},
        )
        counts = {str(row["status"]): int(row["count"]) for row in rows}
        self._execute(
            """
            UPDATE report_batches
            SET queued = :queued, running = :running, completed = :completed, failed = :failed, updated_at = :updated_at
            WHERE id = :id
            """,
            {
                "queued": counts.get("queued", 0),
                "running": counts.get("running", 0),
                "completed": counts.get("completed", 0),
                "failed": counts.get("failed", 0),
                "updated_at": now,
                "id": batch_id,
            },
        )

    def _execute(self, statement: str, params: dict) -> int:
        with self._engine.begin() as connection:
            result = connection.execute(text(statement), params)
            return int(result.rowcount or 0)

    def _fetchone(self, statement: str, params: dict) -> RowMapping | None:
        with self._engine.begin() as connection:
            row = connection.execute(text(statement), params).mappings().fetchone()
            return row

    def _fetchall(self, statement: str, params: dict) -> list[RowMapping]:
        with self._engine.begin() as connection:
            return list(connection.execute(text(statement), params).mappings().fetchall())


def _now() -> str:
    return datetime.now(tz=UTC).isoformat()


def _record_from_row(row: RowMapping) -> ReportRecord:
    return ReportRecord(
        id=int(row["id"]),
        ticker=str(row["ticker"]),
        analysis_date=str(row["analysis_date"]),
        data_source=str(row["data_source"]),
        status=str(row["status"]),
        attempts=int(row["attempts"]),
        max_attempts=int(row["max_attempts"]),
        decision=row["decision"],
        confidence=row["confidence"],
        report_json=row["report_json"],
        markdown=row["markdown"],
        error=row["error"],
        last_error=row["last_error"],
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
        started_at=row["started_at"],
        finished_at=row["finished_at"],
        batch_id=row["batch_id"],
        portfolio_context_json=row["portfolio_context_json"],
    )


def _batch_from_row(row: RowMapping) -> BatchRecord:
    return BatchRecord(
        id=int(row["id"]),
        status=str(row["status"]),
        total=int(row["total"]),
        queued=int(row["queued"]),
        running=int(row["running"]),
        completed=int(row["completed"]),
        failed=int(row["failed"]),
        data_source=str(row["data_source"]),
        requested_analysis_date=row["requested_analysis_date"],
        concurrency=int(row["concurrency"]),
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
        started_at=row["started_at"],
        finished_at=row["finished_at"],
        portfolio_context_json=row["portfolio_context_json"],
    )


def _batch_item_from_row(row: RowMapping) -> BatchItemRecord:
    return BatchItemRecord(
        id=int(row["id"]),
        batch_id=int(row["batch_id"]),
        ticker=str(row["ticker"]),
        status=str(row["status"]),
        analysis_date=row["analysis_date"],
        report_id=row["report_id"],
        decision=row["decision"],
        confidence=row["confidence"],
        error=row["error"],
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
        started_at=row["started_at"],
        finished_at=row["finished_at"],
    )
